# Use postgres/example user/password credentials
version: '3.1'

services:

  postgresdb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: nono
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/library/
    volumes:
      - library:/var/lib/postgresql/data

volumes:
  library: